
package com.andrevilela.cliente;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExemploService", targetNamespace = "http://andrevilela.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExemploService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nome", targetNamespace = "http://andrevilela.com/", className = "com.andrevilela.cliente.Nome")
    @ResponseWrapper(localName = "nomeResponse", targetNamespace = "http://andrevilela.com/", className = "com.andrevilela.cliente.NomeResponse")
    @Action(input = "http://andrevilela.com/ExemploService/nomeRequest", output = "http://andrevilela.com/ExemploService/nomeResponse")
    public String nome();

}
